var json_i18n = {
  theme: "Theme",
  dark_gray: "Dark Gray",
  bright: "Bright",
  dark_blue: "Dark Blue",
  dark_purple: "Dark Purple",
  panels: "Panels",
  items_per_page: "Items per Page",
  tables: "Tables",
  display_tables: "Display Tables",
  ah_small: "Auto-Hide on Small Devices",
  ah_small_title: "Automatically hide tables on small screen devices",
  toggle_panel: "Toggle Panel",
  layout: "Layout",
  horizontal: "Horizontal",
  vertical: "Vertical",
  wide: "WideScreen",
  file_opts: "File Options",
  export_json: "Export as JSON",
  // panel_opts: "Panel Options",
  previous: "Previous",
  next: "Next",
  first: "First",
  last: "Last",
  chart_opts: "Chart Options",
  chart: "Chart",
  type: "Type",
  area_spline: "Area Spline",
  bar: "Bar",
  plot_metric: "Plot Metric",
  table_columns: "Table Columns",
  thead: "Overall Analyzed Requests",
  version: "1.6.4",
};
var html_prefs = {};
var user_interface = {
  general: {
    head: "Overall Analyzed Requests",
    desc: "",
    items: {
      total_requests: {
        className: "black",
        dataType: "numeric",
        label: "Total Requests",
      },
      valid_requests: {
        className: "green",
        dataType: "numeric",
        label: "Normal Requests",
      },
      failed_requests: {
        className: "red",
        dataType: "numeric",
        label: "Anomalous Requests",
      },
      unique_visitors: {
        className: "blue",
        dataType: "numeric",
        label: "Unique Visitors",
      },
      unique_files: { dataType: "numeric", label: "Requested Files" },
    },
  },
  realtime_requests: {
    head: "Total of request in 24 hours",
    desc: "",
    id: "realtime_requests",
    table: 1,
    index: 0,
    perPage: 20,
    panelSize: "large",
    sort: { field: "hits", order: "DESC" },
    plot: [],
    items: [
      {
        colWidth: "3%",
        dataType: "",
        key: "icon",
        label: "",
      },
      {
        colWidth: "6%",
        dataType: "string",
        key: "label",
        label: "Label",
      },
      {
        colWidth: "8%",
        dataType: "string",
        key: "ip",
        label: "IP Addr.",
      },
      {
        colWidth: "12%",
        dataType: "string",
        key: "time",
        label: "Timestamp",
      },
      { colWidth: "6%", dataType: "string", key: "method", label: "Method" },
      {
        colWidth: "8%",
        dataType: "string",
        key: "protocol",
        label: "Protocol",
      },
      {
        colWidth: "7%",
        dataType: "string",
        key: "status",
        label: "Status Code",
      },
      {
        className: "trunc",
        colWidth: "100%",
        meta: "unique",
        metaType: "numeric",
        metaLabel: "Total",
        dataType: "string",
        key: "data",
        label: "Data",
      },
      {
        colWidth: "3%",
        dataType: "numeric",
        key: "index",
        label: "#"
      },
    ],
  },
};

var json_data = {
  general: {
    start_date: "",
    end_date: "",
    date_time: "",
    total_requests: 159,
    valid_requests: 159,
    failed_requests: 0,
    generation_time: 1,
    unique_visitors: 3,
    unique_files: 33,
    excluded_hits: 0,
    unique_referrers: 0,
    unique_not_found: 2,
    unique_static_files: 9,
    log_size: 37400,
    bandwidth: 2259569,
    log_path: ["/var/log/httpd/access_log"],
  },
  realtime_requests: {
    metadata: {
      bytes: {
        total: { value: 2198907 },
        avg: { value: 66633, percent: "3.03" },
        max: { value: 1774419, percent: "80.70" },
        min: { value: 0, percent: "0.00" },
      },
      visitors: {
        total: { value: 48 },
        avg: { value: 1, percent: "2.08" },
        max: { value: 3, percent: "6.25" },
        min: { value: 1, percent: "2.08" },
      },
      hits: {
        total: { value: 119 },
        avg: { value: 3, percent: "2.52" },
        max: { value: 20, percent: "16.81" },
        min: { value: 1, percent: "0.84" },
      },
      data: { total: { value: 33 } },
    },
    data: [],
  },
};
